# Generated by Django 5.2.6 on 2025-10-20 20:58

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id_commande', models.AutoField(primary_key=True, serialize=False)),
                ('numero_commande', models.CharField(max_length=50, unique=True)),
                ('date_commande', models.DateTimeField(auto_now_add=True)),
                ('date_livraison_prevue', models.DateField()),
                ('date_livraison_reelle', models.DateField(blank=True, null=True)),
                ('montant_total', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('envoyee', 'Envoyée'), ('confirmee', 'Confirmée'), ('en_cours', 'En cours de livraison'), ('livree', 'Livrée'), ('annulee', 'Annulée')], default='brouillon', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Commande fournisseur',
                'verbose_name_plural': 'Commandes fournisseurs',
                'db_table': 'commandes_fournisseurs',
                'ordering': ['-date_commande'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id_fournisseur', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('telephone', models.CharField(max_length=20)),
                ('adresse', models.TextField()),
                ('ville', models.CharField(max_length=100)),
                ('pays', models.CharField(default="Côte d'Ivoire", max_length=100)),
                ('delai_livraison_jours', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('montant_commande_min', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('conditions_paiement', models.CharField(max_length=100)),
                ('nb_commandes_total', models.IntegerField(default=0)),
                ('montant_total_achats', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('inactif', 'Inactif')], default='actif', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Fournisseur',
                'verbose_name_plural': 'Fournisseurs',
                'db_table': 'fournisseurs',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id_livraison', models.AutoField(primary_key=True, serialize=False)),
                ('numero_livraison', models.CharField(max_length=50, unique=True)),
                ('date_livraison', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('en_cours', 'En cours'), ('livree', 'Livrée'), ('partielle', 'Livraison partielle'), ('probleme', 'Problème')], default='en_attente', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('receptionnaire', models.CharField(max_length=100)),
                ('id_commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livraisons', to='suppliers.purchaseorder')),
            ],
            options={
                'verbose_name': 'Livraison',
                'verbose_name_plural': 'Livraisons',
                'db_table': 'livraisons',
                'ordering': ['-date_livraison'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderLine',
            fields=[
                ('id_ligne', models.AutoField(primary_key=True, serialize=False)),
                ('quantite', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('sous_total', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('id_commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='suppliers.purchaseorder')),
                ('id_produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lignes_commande_fournisseur', to='products.product')),
            ],
            options={
                'verbose_name': 'Ligne de commande',
                'verbose_name_plural': 'Lignes de commande',
                'db_table': 'lignes_commandes_fournisseurs',
            },
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='id_fournisseur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commandes', to='suppliers.supplier'),
        ),
    ]
