# Generated by Django 5.2.6 on 2025-10-24 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='delivery',
            table='supplier_deliveries',
        ),
        migrations.AlterModelTable(
            name='purchaseorder',
            table='purchase_orders',
        ),
        migrations.AlterModelTable(
            name='purchaseorderline',
            table='purchase_order_lines',
        ),
    ]
