# Generated by Django 5.2.6 on 2025-10-20 20:58

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id_employe', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('telephone', models.CharField(max_length=20)),
                ('adresse', models.TextField(blank=True, null=True)),
                ('date_naissance', models.DateField()),
                ('date_embauche', models.DateField()),
                ('poste', models.CharField(choices=[('caissier', 'Caissier'), ('rayon', 'Responsable rayon'), ('logistique', 'Logistique'), ('manager', 'Manager'), ('rh', 'Ressources Humaines'), ('securite', 'Sécurité')], max_length=50)),
                ('salaire', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('actif', models.BooleanField(default=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='employees/')),
            ],
            options={
                'verbose_name': 'Employé',
                'verbose_name_plural': 'Employés',
                'db_table': 'employes',
                'ordering': ['nom', 'prenom'],
            },
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id_demande', models.AutoField(primary_key=True, serialize=False)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('duree_jours', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('type', models.CharField(choices=[('conges_payes', 'Congés payés'), ('conge_maladie', 'Congé maladie'), ('conge_maternite', 'Congé maternité'), ('conge_paternite', 'Congé paternité'), ('conge_exceptionnel', 'Congé exceptionnel'), ('rtt', 'RTT')], max_length=30)),
                ('motif', models.TextField()),
                ('statut', models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvé'), ('rejected', 'Refusé')], default='pending', max_length=20)),
                ('date_demande', models.DateTimeField(auto_now_add=True)),
                ('valideur', models.CharField(blank=True, max_length=100, null=True)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('id_employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_conges', to='employees.employee')),
            ],
            options={
                'verbose_name': 'Demande de congé',
                'verbose_name_plural': 'Demandes de congés',
                'db_table': 'demandes_conges',
                'ordering': ['-date_demande'],
            },
        ),
        migrations.CreateModel(
            name='PerformanceReview',
            fields=[
                ('id_evaluation', models.AutoField(primary_key=True, serialize=False)),
                ('periode', models.CharField(max_length=20)),
                ('date_evaluation', models.DateField()),
                ('evaluateur', models.CharField(max_length=100)),
                ('score_global', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('score_ponctualite', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('score_qualite_travail', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('score_relationnel', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('score_autonomie', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('points_forts', models.TextField(blank=True, null=True)),
                ('points_amelioration', models.TextField(blank=True, null=True)),
                ('objectifs', models.TextField(blank=True, null=True)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('id_employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='employees.employee')),
            ],
            options={
                'verbose_name': 'Évaluation de performance',
                'verbose_name_plural': 'Évaluations de performance',
                'db_table': 'evaluations_performance',
                'ordering': ['-date_evaluation'],
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id_planning', models.AutoField(primary_key=True, serialize=False)),
                ('jour', models.CharField(choices=[('lundi', 'Lundi'), ('mardi', 'Mardi'), ('mercredi', 'Mercredi'), ('jeudi', 'Jeudi'), ('vendredi', 'Vendredi'), ('samedi', 'Samedi'), ('dimanche', 'Dimanche')], max_length=20)),
                ('shift', models.CharField(choices=[('matin', 'Matin (6h-14h)'), ('apres-midi', 'Après-midi (14h-22h)'), ('nuit', 'Nuit (22h-6h)')], max_length=20)),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('poste_assigne', models.CharField(max_length=100)),
                ('semaine', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(53)])),
                ('annee', models.IntegerField()),
                ('actif', models.BooleanField(default=True)),
                ('id_employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plannings', to='employees.employee')),
            ],
            options={
                'verbose_name': 'Planning',
                'verbose_name_plural': 'Plannings',
                'db_table': 'plannings',
                'ordering': ['annee', 'semaine', 'jour'],
            },
        ),
    ]
