# Generated by Django 5.2.6 on 2025-10-24 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employee_planning_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='departement',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='horaire_debut',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='horaire_fin',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='pause_debut',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='pause_fin',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='statut',
        ),
    ]
