# Generated by Django 5.2.6 on 2025-10-24 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_remove_employee_departement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='departement',
            field=models.CharField(choices=[('caisse', 'Caisse'), ('rayons', 'Rayons'), ('logistique', 'Logistique'), ('administration', 'Administration'), ('securite', 'Sécurité')], default='caisse', max_length=50),
        ),
        migrations.AddField(
            model_name='employee',
            name='horaire_debut',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='horaire_fin',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='pause_debut',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='pause_fin',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='statut',
            field=models.CharField(choices=[('present', 'Présent'), ('absent', 'Absent'), ('conge', 'En congé'), ('malade', 'Malade')], default='present', max_length=20),
        ),
    ]
