# Generated by Django 5.2.6 on 2025-10-20 20:58

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id_client', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('telephone', models.CharField(max_length=20)),
                ('adresse', models.TextField(blank=True, null=True)),
                ('ville', models.CharField(default='Abidjan', max_length=100)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('actif', models.BooleanField(default=True)),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'db_table': 'clients',
                'ordering': ['nom', 'prenom'],
            },
        ),
        migrations.CreateModel(
            name='LoyaltyCard',
            fields=[
                ('id_carte', models.AutoField(primary_key=True, serialize=False)),
                ('numero_carte', models.CharField(max_length=20, unique=True)),
                ('points', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('niveau', models.CharField(choices=[('bronze', 'Bronze'), ('argent', 'Argent'), ('or', 'Or'), ('platine', 'Platine')], default='bronze', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_expiration', models.DateField(blank=True, null=True)),
                ('actif', models.BooleanField(default=True)),
                ('id_client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='carte_fidelite', to='customers.client')),
            ],
            options={
                'verbose_name': 'Carte de fidélité',
                'verbose_name_plural': 'Cartes de fidélité',
                'db_table': 'cartes_fidelite',
            },
        ),
        migrations.CreateModel(
            name='LoyaltyTransaction',
            fields=[
                ('id_transaction_fidelite', models.AutoField(primary_key=True, serialize=False)),
                ('type_transaction', models.CharField(choices=[('gain', 'Gain de points'), ('utilisation', 'Utilisation de points'), ('expiration', 'Expiration de points'), ('ajustement', 'Ajustement')], max_length=20)),
                ('points', models.IntegerField()),
                ('points_avant', models.IntegerField()),
                ('points_apres', models.IntegerField()),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('reference_vente', models.CharField(blank=True, max_length=100, null=True)),
                ('date_transaction', models.DateTimeField(auto_now_add=True)),
                ('id_carte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='customers.loyaltycard')),
            ],
            options={
                'verbose_name': 'Transaction de fidélité',
                'verbose_name_plural': 'Transactions de fidélité',
                'db_table': 'transactions_fidelite',
                'ordering': ['-date_transaction'],
            },
        ),
    ]
