# Generated by Django 5.2.6 on 2025-10-20 21:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id_reclamation', models.AutoField(primary_key=True, serialize=False)),
                ('sujet', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('priorite', models.CharField(choices=[('basse', 'Basse'), ('moyenne', 'Moyenne'), ('haute', 'Haute'), ('urgente', 'Urgente')], default='moyenne', max_length=20)),
                ('statut', models.CharField(choices=[('ouverte', 'Ouverte'), ('en_cours', 'En cours de traitement'), ('resolue', 'Résolue'), ('fermee', 'Fermée')], default='ouverte', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_resolution', models.DateTimeField(blank=True, null=True)),
                ('responsable', models.CharField(blank=True, max_length=100, null=True)),
                ('reponse', models.TextField(blank=True, null=True)),
                ('id_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reclamations', to='customers.client')),
            ],
            options={
                'verbose_name': 'Réclamation',
                'verbose_name_plural': 'Réclamations',
                'db_table': 'reclamations',
                'ordering': ['-date_creation'],
            },
        ),
    ]
