# Generated by Django 5.2.6 on 2025-10-20 20:58

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('employees', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashRegister',
            fields=[
                ('id_caisse', models.AutoField(primary_key=True, serialize=False)),
                ('numero_caisse', models.CharField(max_length=20, unique=True)),
                ('emplacement', models.CharField(max_length=100)),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Caisse',
                'verbose_name_plural': 'Caisses',
                'db_table': 'caisses',
                'ordering': ['numero_caisse'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id_transaction', models.AutoField(primary_key=True, serialize=False)),
                ('numero_ticket', models.CharField(max_length=50, unique=True)),
                ('date_transaction', models.DateTimeField(auto_now_add=True)),
                ('montant_total', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('montant_remise', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('montant_final', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('points_utilises', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('points_gagnes', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('terminee', 'Terminée'), ('annulee', 'Annulée'), ('suspendue', 'Suspendue')], default='en_cours', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('id_caisse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='sales.cashregister')),
                ('id_caissier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='employees.employee')),
                ('id_client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='customers.client')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'db_table': 'transactions',
                'ordering': ['-date_transaction'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id_paiement', models.AutoField(primary_key=True, serialize=False)),
                ('mode_paiement', models.CharField(choices=[('especes', 'Espèces'), ('carte', 'Carte bancaire'), ('mobile', 'Mobile Money'), ('cheque', 'Chèque')], max_length=20)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('reference', models.CharField(blank=True, max_length=100, null=True)),
                ('date_paiement', models.DateTimeField(auto_now_add=True)),
                ('id_transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='sales.transaction')),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
                'db_table': 'paiements',
                'ordering': ['-date_paiement'],
            },
        ),
        migrations.CreateModel(
            name='TransactionLine',
            fields=[
                ('id_ligne', models.AutoField(primary_key=True, serialize=False)),
                ('quantite', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('prix_promotion', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('sous_total', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('remise_appliquee', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('id_produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lignes_vente', to='products.product')),
                ('id_transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='sales.transaction')),
            ],
            options={
                'verbose_name': 'Ligne de transaction',
                'verbose_name_plural': 'Lignes de transaction',
                'db_table': 'lignes_transactions',
            },
        ),
    ]
