# Generated by Django 5.2.6 on 2025-10-20 20:58

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id_categorie', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
                'db_table': 'categories',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id_produit', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('code_barre', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('prix_achat', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('stock', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('seuil_reapprovisionnement', models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('est_perissable', models.BooleanField(default=False)),
                ('date_expiration', models.DateField(blank=True, null=True)),
                ('unite_mesure', models.CharField(default='unité', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='produits/')),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('id_categorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produits', to='products.category')),
            ],
            options={
                'verbose_name': 'Produit',
                'verbose_name_plural': 'Produits',
                'db_table': 'produits',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id_mouvement', models.AutoField(primary_key=True, serialize=False)),
                ('type_mouvement', models.CharField(choices=[('entree', 'Entrée'), ('sortie', 'Sortie'), ('ajustement', 'Ajustement'), ('retour', 'Retour')], max_length=20)),
                ('quantite', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('stock_avant', models.IntegerField()),
                ('stock_apres', models.IntegerField()),
                ('motif', models.CharField(blank=True, max_length=200, null=True)),
                ('reference', models.CharField(blank=True, max_length=100, null=True)),
                ('date_mouvement', models.DateTimeField(auto_now_add=True)),
                ('id_produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mouvements', to='products.product')),
            ],
            options={
                'verbose_name': 'Mouvement de stock',
                'verbose_name_plural': 'Mouvements de stock',
                'db_table': 'mouvements_stock',
                'ordering': ['-date_mouvement'],
            },
        ),
    ]
